// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATCEWAh7i5TzKt6ec7LWGaz8yRkPOskfE',
    appId: '1:800670612727:web:e160ac028a18e2667c27f2',
    messagingSenderId: '800670612727',
    projectId: 'blinksy-dd52f',
    authDomain: 'blinksy-dd52f.firebaseapp.com',
    storageBucket: 'blinksy-dd52f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnvc-gOZao815m21-Tz-CTpw2tLtG7PqY',
    appId: '1:800670612727:android:1ceeeb3558a0389d7c27f2',
    messagingSenderId: '800670612727',
    projectId: 'blinksy-dd52f',
    storageBucket: 'blinksy-dd52f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgrspMIHxcozD6hgGimk8O7BM2wg-A4bI',
    appId: '1:800670612727:ios:3c7ea89ded49c9547c27f2',
    messagingSenderId: '800670612727',
    projectId: 'blinksy-dd52f',
    storageBucket: 'blinksy-dd52f.firebasestorage.app',
    iosBundleId: 'com.example.blinksy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgrspMIHxcozD6hgGimk8O7BM2wg-A4bI',
    appId: '1:800670612727:ios:3c7ea89ded49c9547c27f2',
    messagingSenderId: '800670612727',
    projectId: 'blinksy-dd52f',
    storageBucket: 'blinksy-dd52f.firebasestorage.app',
    iosBundleId: 'com.example.blinksy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATCEWAh7i5TzKt6ec7LWGaz8yRkPOskfE',
    appId: '1:800670612727:web:2b3f0fae113379bd7c27f2',
    messagingSenderId: '800670612727',
    projectId: 'blinksy-dd52f',
    authDomain: 'blinksy-dd52f.firebaseapp.com',
    storageBucket: 'blinksy-dd52f.firebasestorage.app',
  );

}